name: 'Nightly Publish'

on: push

jobs:
  nightly-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Publish
      run: |
        git clone https://github.com/NaomiProject/Naomi.git
        cd Naomi
        git checkout naomi-dev
        git pull
        cd ../
        mv Naomi Naomi-Nightly
        zip -r Naomi-Nightly.zip Naomi-Nightly
        mv Naomi-Nightly.zip Naomi-Nightly/installers/

    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "Naomi-Nightly/installers/"